---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Cameron Lara"
pagetitle: "L01 Cameron Lara"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Cameron's L01 GitHub Repo](https://github.com/stat301-3-2026-spring/l01-review-camjlara41.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution
1. data cleaning/eda
2. initial setup (splitting, folding)
3. building recipes (including a baseline recipe and tree versions for each additional recipe)
4. fit models to resamples or tuning grids on training set
5. analyze all model results and choose best model
6. fit final model to testing set
:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution
Supervised learning means that desired outcome variables are provided to the model. Unsupervised learning means that the model determines relationships in the data on its own.
:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution
Describe characteristics and trends in the data.
:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution
Create a model that answers a research question/hypothesis, such as a specific variable's importance in predicting for an outcome variable
:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution
Create a model that yields the most accurate prediction on new data.
:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution
Mechanistic models utilize a predetermined equation in order to make a prediction.
:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution
Empirically driven models do not assume a known equation and instead make predictions based only on given data.
:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution
Mechanistic models are parametric and empirically driven models are nonparametric.
:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution
In general, a mechanistic model is easier to interpret because the form of the relationship between variables (or the equation) is already known.
:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution
Because the form of the relationship between variables in empirically driven models is determined by the given data, empirically driven models are generally more flexible.
:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution
Because mechanistic models follow a known equation, they are generally less flexible and thus have less variance and are more biased. Meanwhile, empirically driven models tend to be more flexible and thus have greater variance and are less biased.
:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution
Regression ML problems aim to predict a value of a continuous outcome variable while classification ML problems aim to predict a class of a discrete outcome variable.
:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution
It is useful to stratify by the outcome variable when splitting the data because it ensures that the distribution of the outcome variable is consistent from the full data set to the training and testing sets.
:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution
This is an inferential question because it aims to determine whether a certain predictor variable (number of service calls) is relevant in predicting the 
:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::
