---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 3 with R 
  | STAT 301-3
author: "Cameron Lara"
pagetitle: "Self Evaluation L01 Cameron Lara"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Cameron's L01 GitHub Repo](https://github.com/stat301-3-2026-spring/l01-review-camjlara41.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution
1. data cleaning/eda
2. initial setup (splitting, folding)
3. building recipes (including a baseline recipe and tree versions for each additional recipe)
4. fit models to resamples or tuning grids on training set
5. analyze all model results and choose best model
6. fit final model to testing set
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution
Supervised learning means that desired outcome variables are provided to the model. Unsupervised learning means that the model determines relationships in the data on its own.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution
Describe characteristics and trends in the data.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution
Create a model that answers a research question/hypothesis, such as a specific variable's importance in predicting for an outcome variable
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution
Create a model that yields the most accurate prediction on new data.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution
Mechanistic models utilize a predetermined equation in order to make a prediction.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution
Empirically driven models do not assume a known equation and instead make predictions based only on given data.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution
Mechanistic models are parametric and empirically driven models are nonparametric.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution
In general, a mechanistic model is easier to interpret because the form of the relationship between variables (or the equation) is already known.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution
Because the form of the relationship between variables in empirically driven models is determined by the given data, empirically driven models are generally more flexible.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution
Because mechanistic models follow a known equation, they are generally less flexible and thus have less variance and are more biased. Meanwhile, empirically driven models tend to be more flexible and thus have greater variance and are less biased.
:::

#### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution
Regression ML problems aim to predict a value of a continuous outcome variable while classification ML problems aim to predict a class of a discrete outcome variable.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution
It is useful to stratify by the outcome variable when splitting the data because it ensures that the distribution of the outcome variable is consistent from the full data set to the training and testing sets.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution
V-fold cross validation splits the training set into a certain number of subsets (V), fitting and training the model on all but one of those subsets, which is used as the "testing"/evaluation set. Each subset is used as the evaluation set once, and the process can be repeated a certain number of times (repeats). An evaluation metric is obtained for each subset and repeat, and these metrics are averaged to produce a single metric. This allows us to gauge the initial efficacy of each model without yet evaluating them on the final testing set, which would lead to data leakage.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution
You might use bootstrap resampling in cases where you have a very small number of observations and splitting the data into subsets is not feasible. This is because bootstrap resampling takes individual samples of the training set with replacement for each additional resample.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution
Model tuning is the process of adjusting the hyperparameter ranges of a model. We use model tuning because it allows us to create models better suited for prediction accuracy in a given dataset. Hyperparameters can be refined by analyzing the best hyperparameters in prior prediction results.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution
Two common performance metric for regression ML problems are RMSE and MAE.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution
Two common performance metrics for classification ML problems are accuracy and ROC-AUC.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution
This is an inferential question because it asks a research question, aiming to determine whether a certain predictor variable (number of service calls) is relevant in predicting the likelihood of a customer dropping the service.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution
This is a prediction question because it aims to yield the most accurate prediction of whether a customer will drop the service as possible.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::
